---
title: "spotify dplyr"
author: "Arina Agaronyan"
format: 
  html: 
    echo: false 
  pdf: 
    echo: false
---


```{r config}
#| message: false
here::i_am("dplyr homework.Rproj")
library(here)
library(ggplot2)
theme_set(theme_bw())
library(dplyr)
library(tidyr)
library(knitr)
options(dplyr.summarise.inform = FALSE)
```


## Exercise 1

```{r load_spotify}
spotify <- readRDS(here("top-spotify-songs-from-20102019-by-year.Rds"))
```



### Q1

```{r q1}
n_song <- spotify %>% distinct(title)
n_artist <- spotify %>% distinct(artist)
n_genre <- spotify %>% distinct(`top genre`)
```

The data set contains `r nrow(n_song)` songs, `r nrow(n_artist)` artists, and `r nrow(n_genre)` musical genres.



### Q2

```{r n_songs_per_year}
knitr::kable(spotify %>% count(year), col.names = c("Year", "Number of songs per year"))
```



### Q3

```{r pop_artist}
n_song_all <- spotify %>% distinct(title, .keep_all = TRUE)
sp_stats <- n_song_all |>
  group_by(artist) |>
  summarise(N=n()) |>
  slice_max(order_by = N)
```

The most popular artist is `r sp_stats[1]`, with `r sp_stats[2]` individual songs on the spotify top song charts.



### Q4

```{r bpm_stats}
knitr::kable(n_song_all |>
  group_by(`top genre`) |>
  summarise(min(bpm), max(bpm), mean(bpm), median(bpm), "n of songs"=n()))
```



### Q5

```{r nrg_stats}
nrg_dnc_stats <- spotify |>
  group_by(year) |>
  summarise(median(nrgy), median(dnce))
knitr::kable(nrg_dnc_stats) #necessary or not?
```



### Q6

```{r longer_nrgy_stats}
longstats <- 
  nrg_dnc_stats |>
  pivot_longer(-year, names_to = "Statistic")
```

```{r longstats_nrg}
ggplot(longstats, aes(x=year, y=value, group=Statistic, color=Statistic))+
  geom_line() +
  labs(title = "Temporal evolution of the median annual energy and the
median annual danceability.", y = "%")
```



## Exercise 2

```{r load_dropout}
dropout <- readRDS(here("dropout.rds"))
```



### Q1

```{r med_age}
med_age <- 
  dropout %>%
  group_by(Gender, `Marital status`) %>%
  summarise(median(`Age at enrollment`))
```

  

### Q2
  
```{r med_age_table}
knitr::kable(med_age|>
  pivot_wider(names_from = Gender, values_from = `median(\`Age at enrollment\`)`), caption = "Median age at enrollment")
```



### Q3

```{r mean_curr}
curr_mean <- 
  dropout |>
  group_by(Target) |>
  select(starts_with("Curricular")) |>
  summarise(across(where(is.numeric), mean)) 
```



